name: stories_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  orm: ^5.3.3
  json_annotation: ^4.9.0
  dotenv: ^4.2.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  json_serializable: ^6.9.2
  build_runner: ^2.4.15  
